config/routes.rb
Rails.application.routes.draw do
  resources :two_outputs
  resources :two_criteria
  resources :two_results
  resources :three_results
  resources :four_results
  resources :five_results
  resources :six_results

  get '/auto6', to: 'six_results#auto6'
  get '/auto5', to: 'five_results#auto5'
  get '/auto4', to: 'four_results#auto4'
  get '/auto3', to: 'three_results#auto3'
  #get '/auto2', to: 'two_results#auto2'
  get '/auto2', to: 'application#auto2'

  get '/output2', to: 'two_outputs#output2'

  #get '/', to: 'application#dashboard'
  get '/combinations', to: 'application#combinations'
  get '/results', to: 'application#results'
  get '/criteria', to: 'appliciation#criteria'
  get '/test_database_progress', to: 'application#test_database_progress'
  get '/sample', to: 'application#sample'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#hello'
  get 'pdf', to: 'application#pdf'
  get 'input', to: 'application#input'
  get 'input2', to: 'application#input2'

  get 'two_results/newa', to: 'two_results#newa'
end

app/models/six_result.rb
class SixResult < ApplicationRecord

	def autosix


	end
end

app/controllers/six_results_controller.rb
class SixResultsController < ApplicationController
  before_action :set_six_result, only: [:show, :edit, :update, :destroy]

  
  def auto6    
    for fRes in 1..10
      for eRes in 1..10
        for dRes in 1..10
         for cRes in 1..10 
          for bRes in 1..10
            for aRes in 1..10
              @six_result = SixResult.new({"R1"=>aRes, "R2"=>bRes, "R3"=>cRes, "R4"=>dRes, "R5"=>eRes, "R6"=>fRes})
              @six_result.save
            end
          end
        end
      end
    end
  end
end

  # GET /six_results
  # GET /six_results.json
  def index
    @six_results = SixResult.all
  end

  # GET /six_results/1
  # GET /six_results/1.json
  def show
  end

  # GET /six_results/new
  def new
    @six_result = SixResult.new
  end

  # GET /six_results/1/edit
  def edit
  end

  # POST /six_results
  # POST /six_results.json
  def create
    @six_result = SixResult.new(six_result_params)

    respond_to do |format|
      if @six_result.save
        format.html { redirect_to @six_result, notice: 'Six result was successfully created.' }
        format.json { render :show, status: :created, location: @six_result }
      else
        format.html { render :new }
        format.json { render json: @six_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /six_results/1
  # PATCH/PUT /six_results/1.json
  def update
    respond_to do |format|
      if @six_result.update(six_result_params)
        format.html { redirect_to @six_result, notice: 'Six result was successfully updated.' }
        format.json { render :show, status: :ok, location: @six_result }
      else
        format.html { render :edit }
        format.json { render json: @six_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /six_results/1
  # DELETE /six_results/1.json
  def destroy
    @six_result.destroy
    respond_to do |format|
      format.html { redirect_to six_results_url, notice: 'Six result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_six_result
      @six_result = SixResult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def six_result_params
      params.require(:six_result).permit(:R1, :R2, :R3, :R4, :R5, :R6)
    end
end

app/helpers/six_results_helper.rb
module SixResultsHelper
end

app/views/six_results/_form.html.erb
<%= form_for(six_result) do |f| %>
  <% if six_result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(six_result.errors.count, "error") %> prohibited this six_result from being saved:</h2>

      <ul>
      <% six_result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :R1 %>
    <%= f.number_field :R1 %>
  </div>

  <div class="field">
    <%= f.label :R2 %>
    <%= f.number_field :R2 %>
  </div>

  <div class="field">
    <%= f.label :R3 %>
    <%= f.number_field :R3 %>
  </div>

  <div class="field">
    <%= f.label :R4 %>
    <%= f.number_field :R4 %>
  </div>

  <div class="field">
    <%= f.label :R5 %>
    <%= f.number_field :R5 %>
  </div>

  <div class="field">
    <%= f.label :R6 %>
    <%= f.number_field :R6 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/six_results/auto.html.erb
<h1>Auto Six Result</h1>


<%= link_to 'Back', six_results_path %>

app/views/six_results/edit.html.erb
<h1>Editing Six Result</h1>

<%= render 'form', six_result: @six_result %>

<%= link_to 'Show', @six_result %> |
<%= link_to 'Back', six_results_path %>

app/views/six_results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Six Results</h1>

<table>
  <thead>
    <tr>
      <th>R1</th>
      <th>R2</th>
      <th>R3</th>
      <th>R4</th>
      <th>R5</th>
      <th>R6</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @six_results.each do |six_result| %>
      <tr>
        <td><%= six_result.R1 %></td>
        <td><%= six_result.R2 %></td>
        <td><%= six_result.R3 %></td>
        <td><%= six_result.R4 %></td>
        <td><%= six_result.R5 %></td>
        <td><%= six_result.R6 %></td>
        <td><%= link_to 'Show', six_result %></td>
        <td><%= link_to 'Edit', edit_six_result_path(six_result) %></td>
        <td><%= link_to 'Destroy', six_result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Six Result', new_six_result_path %>
<%= link_to 'Auto Creation', '/auto6' %>

app/views/six_results/new.html.erb
<h1>New Six Result</h1>

<%= render 'form', six_result: @six_result %>

<%= link_to 'Back', six_results_path %>

app/views/six_results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>R1:</strong>
  <%= @six_result.R1 %>
</p>

<p>
  <strong>R2:</strong>
  <%= @six_result.R2 %>
</p>

<p>
  <strong>R3:</strong>
  <%= @six_result.R3 %>
</p>

<p>
  <strong>R4:</strong>
  <%= @six_result.R4 %>
</p>

<p>
  <strong>R5:</strong>
  <%= @six_result.R5 %>
</p>

<p>
  <strong>R6:</strong>
  <%= @six_result.R6 %>
</p>

<%= link_to 'Edit', edit_six_result_path(@six_result) %> |
<%= link_to 'Back', six_results_path %>