config/routes.rb
Rails.application.routes.draw do
  resources :two_outputs
  resources :two_criteria
  resources :two_results
  resources :three_results
  resources :four_results
  resources :five_results
  resources :six_results

  get '/auto6', to: 'six_results#auto6'
  get '/auto5', to: 'five_results#auto5'
  get '/auto4', to: 'four_results#auto4'
  get '/auto3', to: 'three_results#auto3'
  #get '/auto2', to: 'two_results#auto2'
  get '/auto2', to: 'application#auto2'

  get '/output2', to: 'two_outputs#output2'

  #get '/', to: 'application#dashboard'
  get '/combinations', to: 'application#combinations'
  get '/results', to: 'application#results'
  get '/criteria', to: 'appliciation#criteria'
  get '/test_database_progress', to: 'application#test_database_progress'
  get '/sample', to: 'application#sample'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#hello'
  get 'pdf', to: 'application#pdf'
  get 'input', to: 'application#input'
  get 'input2', to: 'application#input2'

  get 'two_results/newa', to: 'two_results#newa'
end

app/models/four_result.rb
class FourResult < ApplicationRecord
end

app/controllers/four_results_controller.rb
class FourResultsController < ApplicationController
  before_action :set_four_result, only: [:show, :edit, :update, :destroy]

  # GET /four_results
  # GET /four_results.json
  def index
    @four_results = FourResult.all
  end

  # GET /four_results/1
  # GET /four_results/1.json
  def show
  end

  # GET /four_results/new
  def new
    @four_result = FourResult.new
  end

  # GET /four_results/1/edit
  def edit
  end

  # POST /four_results
  # POST /four_results.json
  def create
    @four_result = FourResult.new(four_result_params)

    respond_to do |format|
      if @four_result.save
        format.html { redirect_to @four_result, notice: 'Four result was successfully created.' }
        format.json { render :show, status: :created, location: @four_result }
      else
        format.html { render :new }
        format.json { render json: @four_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /four_results/1
  # PATCH/PUT /four_results/1.json
  def update
    respond_to do |format|
      if @four_result.update(four_result_params)
        format.html { redirect_to @four_result, notice: 'Four result was successfully updated.' }
        format.json { render :show, status: :ok, location: @four_result }
      else
        format.html { render :edit }
        format.json { render json: @four_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /four_results/1
  # DELETE /four_results/1.json
  def destroy
    @four_result.destroy
    respond_to do |format|
      format.html { redirect_to four_results_url, notice: 'Four result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_four_result
      @four_result = FourResult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def four_result_params
      params.require(:four_result).permit(:R1, :R2, :R3, :R4)
    end
end

app/helpers/four_results_helper.rb
module FourResultsHelper
end

app/views/four_results/_form.html.erb
<%= form_for(four_result) do |f| %>
  <% if four_result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(four_result.errors.count, "error") %> prohibited this four_result from being saved:</h2>

      <ul>
      <% four_result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :R1 %>
    <%= f.number_field :R1 %>
  </div>

  <div class="field">
    <%= f.label :R2 %>
    <%= f.number_field :R2 %>
  </div>

  <div class="field">
    <%= f.label :R3 %>
    <%= f.number_field :R3 %>
  </div>

  <div class="field">
    <%= f.label :R4 %>
    <%= f.number_field :R4 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/four_results/edit.html.erb
<h1>Editing Four Result</h1>

<%= render 'form', four_result: @four_result %>

<%= link_to 'Show', @four_result %> |
<%= link_to 'Back', four_results_path %>

app/views/four_results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Four Results</h1>

<table>
  <thead>
    <tr>
      <th>R1</th>
      <th>R2</th>
      <th>R3</th>
      <th>R4</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @four_results.each do |four_result| %>
      <tr>
        <td><%= four_result.R1 %></td>
        <td><%= four_result.R2 %></td>
        <td><%= four_result.R3 %></td>
        <td><%= four_result.R4 %></td>
        <td><%= link_to 'Show', four_result %></td>
        <td><%= link_to 'Edit', edit_four_result_path(four_result) %></td>
        <td><%= link_to 'Destroy', four_result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Four Result', new_four_result_path %>

app/views/four_results/new.html.erb
<h1>New Four Result</h1>

<%= render 'form', four_result: @four_result %>

<%= link_to 'Back', four_results_path %>

app/views/four_results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>R1:</strong>
  <%= @four_result.R1 %>
</p>

<p>
  <strong>R2:</strong>
  <%= @four_result.R2 %>
</p>

<p>
  <strong>R3:</strong>
  <%= @four_result.R3 %>
</p>

<p>
  <strong>R4:</strong>
  <%= @four_result.R4 %>
</p>

<%= link_to 'Edit', edit_four_result_path(@four_result) %> |
<%= link_to 'Back', four_results_path %>