config/routes.rb
Rails.application.routes.draw do
  resources :two_outputs
  resources :two_criteria
  resources :two_results
  resources :three_results
  resources :four_results
  resources :five_results
  resources :six_results

  get '/auto6', to: 'six_results#auto6'
  get '/auto5', to: 'five_results#auto5'
  get '/auto4', to: 'four_results#auto4'
  get '/auto3', to: 'three_results#auto3'
  #get '/auto2', to: 'two_results#auto2'
  get '/auto2', to: 'application#auto2'

  get '/output2', to: 'two_outputs#output2'

  #get '/', to: 'application#dashboard'
  get '/combinations', to: 'application#combinations'
  get '/results', to: 'application#results'
  get '/criteria', to: 'appliciation#criteria'
  get '/test_database_progress', to: 'application#test_database_progress'
  get '/sample', to: 'application#sample'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#hello'
  get 'pdf', to: 'application#pdf'
  get 'input', to: 'application#input'
  get 'input2', to: 'application#input2'

  get 'two_results/newa', to: 'two_results#newa'
end

app/models/two_output.rb
class TwoOutput < ApplicationRecord
end

app/controllers/two_outputs_controller.rb
class TwoOutputsController < ApplicationController
  before_action :set_two_output, only: [:show, :edit, :update, :destroy]
  

  # GET /two_outputs
  # GET /two_outputs.json
  def index
    @two_outputs = TwoOutput.all
  end

  # GET /two_outputs/1
  # GET /two_outputs/1.json
  def show
  end

  # GET /two_outputs/new
  def new
    @two_output = TwoOutput.new
  end

  # GET /two_outputs/1/edit
  def edit
  end

  # POST /two_outputs
  # POST /two_outputs.json
  def create
    @two_output = TwoOutput.new(two_output_params)

    respond_to do |format|
      if @two_output.save
        format.html { redirect_to @two_output, notice: 'Two output was successfully created.' }
        format.json { render :show, status: :created, location: @two_output }
      else
        format.html { render :new }
        format.json { render json: @two_output.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /two_outputs/1
  # PATCH/PUT /two_outputs/1.json
  def update
    respond_to do |format|
      if @two_output.update(two_output_params)
        format.html { redirect_to @two_output, notice: 'Two output was successfully updated.' }
        format.json { render :show, status: :ok, location: @two_output }
      else
        format.html { render :edit }
        format.json { render json: @two_output.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /two_outputs/1
  # DELETE /two_outputs/1.json
  def destroy
    @two_output.destroy
    respond_to do |format|
      format.html { redirect_to two_outputs_url, notice: 'Two output was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_two_output
      @two_output = TwoOutput.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def two_output_params
      params.require(:two_output).permit(:O1, :O2)
    end
end

app/helpers/two_outputs_helper.rb
module TwoOutputsHelper
end

app/views/two_outputs/_form.html.erb
<%= form_for(two_output) do |f| %>
  <% if two_output.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(two_output.errors.count, "error") %> prohibited this two_output from being saved:</h2>

      <ul>
      <% two_output.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :O1 %>
    <%= f.number_field :O1 %>
  </div>

  <div class="field">
    <%= f.label :O2 %>
    <%= f.number_field :O2 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/two_outputs/edit.html.erb
<h1>Editing Two Output</h1>

<%= render 'form', two_output: @two_output %>

<%= link_to 'Show', @two_output %> |
<%= link_to 'Back', two_outputs_path %>

app/views/two_outputs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Two Outputs</h1>

<table>
  <thead>
    <tr>
      <th>O1</th>
      <th>O2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @two_outputs.each do |two_output| %>
      <tr>
        <td><%= two_output.O1 %></td>
        <td><%= two_output.O2 %></td>
        <td><%= link_to 'Show', two_output %></td>
        <td><%= link_to 'Edit', edit_two_output_path(two_output) %></td>
        <td><%= link_to 'Destroy', two_output, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Two Output', new_two_output_path %>
<%= link_to 'Find Matching Combinations', '/test_database_progress' %>
<%= link_to 'Find Matching Combinations', '/auto2' %>

app/views/two_outputs/new.html.erb
<h1>New Two Output</h1>

<%= render 'form', two_output: @two_output %>

<%= link_to 'Back', two_outputs_path %>

app/views/two_outputs/output2.html.erb
<h1>Output Two Result</h1>


<%= link_to 'Back', two_outputs_path %>

app/views/two_outputs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>O1:</strong>
  <%= @two_output.O1 %>
</p>

<p>
  <strong>O2:</strong>
  <%= @two_output.O2 %>
</p>

<%= link_to 'Edit', edit_two_output_path(@two_output) %> |
<%= link_to 'Back', two_outputs_path %>