config/routes.rb
Rails.application.routes.draw do
  resources :two_outputs
  resources :two_criteria
  resources :two_results
  resources :three_results
  resources :four_results
  resources :five_results
  resources :six_results

  get '/auto6', to: 'six_results#auto6'
  get '/auto5', to: 'five_results#auto5'
  get '/auto4', to: 'four_results#auto4'
  get '/auto3', to: 'three_results#auto3'
  #get '/auto2', to: 'two_results#auto2'
  get '/auto2', to: 'application#auto2'

  get '/output2', to: 'two_outputs#output2'

  #get '/', to: 'application#dashboard'
  get '/combinations', to: 'application#combinations'
  get '/results', to: 'application#results'
  get '/criteria', to: 'appliciation#criteria'
  get '/test_database_progress', to: 'application#test_database_progress'
  get '/sample', to: 'application#sample'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#hello'
  get 'pdf', to: 'application#pdf'
  get 'input', to: 'application#input'
  get 'input2', to: 'application#input2'

  get 'two_results/newa', to: 'two_results#newa'
end

app/models/two_result.rb
class TwoResult < ApplicationRecord
end

app/controllers/two_results_controller.rb
class TwoResultsController < ApplicationController
  before_action :set_two_result, only: [:show, :edit, :update, :destroy]


  # GET /two_results
  # GET /two_results.json
  def index
    @two_results = TwoResult.all
  end

  # GET /two_results/1
  # GET /two_results/1.json
  def show
  end

  # GET /two_results/new
  def new
    @two_result = TwoResult.new
  end

  def newb
    p "made it"
  end

  # GET /two_results/1/edit
  def edit
  end

  # POST /two_results
  # POST /two_results.json
  def create
    @two_result = TwoResult.new(two_result_params)

    respond_to do |format|
      if @two_result.save
        format.html { redirect_to '/two_result/'+ TwoResult.find(params[:id]) + '/edit', notice: 'Two result was successfully created.' }
        format.json { render :show, status: :created, location: @two_result }
      else
        format.html { render :new }
        format.json { render json: @two_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /two_results/1
  # PATCH/PUT /two_results/1.json
  def update
    respond_to do |format|
      if @two_result.update(two_result_params)
        format.html { redirect_to @two_result, notice: 'Two result was successfully updated.' }
        format.json { render :show, status: :ok, location: @two_result }
      else
        format.html { render :edit }
        format.json { render json: @two_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /two_results/1
  # DELETE /two_results/1.json
  def destroy
    @two_result.destroy
    respond_to do |format|
      format.html { redirect_to two_results_url, notice: 'Two result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_two_result
      @two_result = TwoResult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def two_result_params
      params.require(:two_result).permit(:R1, :R2)
    end
end

app/helpers/two_results_helper.rb
module TwoResultsHelper
end

app/views/two_results/_form.html.erb
<%= form_for(two_result) do |f| %>
  <% if two_result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(two_result.errors.count, "error") %> prohibited this two_result from being saved:</h2>

      <ul>
      <% two_result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :R1 %>
    <%= f.number_field :R1 %>
  </div>

  <div class="field">
    <%= f.label :R2 %>
    <%= f.number_field :R2 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/two_results/_form2.html.erb
<%= form_for(two_result) do |f| %>
  <% if two_result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(two_result.errors.count, "error") %> prohibited this two_result from being saved:</h2>

      <ul>
      <% two_result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :R2 %>
    <%= f.number_field :R2 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/two_results/auto2.html.erb
<h1>Auto Two Result</h1>
<table>
  <thead>
    <tr>
      <th>R1</th>
      <th>R2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @two_results.each do |two_result| %>
      <tr>
        <td><%= two_result.R1 %></td>
        <td><%= two_result.R2 %></td>
        <td><%= link_to 'Show', two_result %></td>
        <td><%= link_to 'Edit', edit_two_result_path(two_result) %></td>
        <td><%= link_to 'Destroy', two_result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', two_results_path %>

app/views/two_results/edit.html.erb
<h1>Editing Two Result</h1>

<%= render 'form2', two_result: @two_result %>

<%= link_to 'Show', @two_result %> |
<%= link_to 'Back', two_results_path %>

app/views/two_results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Two Results</h1>

<table>
  <thead>
    <tr>
      <th>R1</th>
      <th>R2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @two_results.each do |two_result| %>
      <tr>
        <td><%= two_result.R1 %></td>
        <td><%= two_result.R2 %></td>
        <td><%= link_to 'Show', two_result %></td>
        <td><%= link_to 'Edit', edit_two_result_path(two_result) %></td>
        <td><%= link_to 'Destroy', two_result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Two Result', new_two_result_path %>
<%= link_to 'Auto Creation', '/auto2' %>

app/views/two_results/new.html.erb
<h1>New Two Result</h1>

<%= render 'form', two_result: @two_result %>

<%= link_to 'Back', two_results_path %>

app/views/two_results/newa.html.erb
<h1>New Two Result 2</h1>

<%= render 'form2', two_result: @two_result %>

<%= link_to 'Back', two_results_path %>

app/views/two_results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>R1:</strong>
  <%= @two_result.R1 %>
</p>

<p>
  <strong>R2:</strong>
  <%= @two_result.R2 %>
</p>

<%= link_to 'Edit', edit_two_result_path(@two_result) %> |
<%= link_to 'Back', two_results_path %>